blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView
app_name = BlogConfig.name



urlpatterns = [
    path("blogs/", cache_page(60)(BlogListView.as_view()), name="blogs"),
    path("blog/detail/<int:pk>/", BlogDetailView.as_view(), name="detail")

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static 
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("servise.urls")),
    path('users/', include("users.urls", namespace='users')),
    path('blog/', include('blog.urls')),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from users.views import RegisterView, UserListView, ActivateUser
from servise.views import HomeView
from users.apps import UsersConfig
app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('register/', RegisterView.as_view(), name="regyster"),
    path("userslist/", UserListView.as_view(), name="userslist"),
    path("userbloc/<int:pk>/", ActivateUser, name="block")
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True, 'null': True}

class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')
    fio = models.CharField(max_length=150, verbose_name='ФИО')
    comment = models.TextField(verbose_name='коментарий', **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from users.models import User

class UserRegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ("email", "password1", "password2")

users/views.py
from django.views.generic import (ListView, 
                                  DetailView, 
                                  TemplateView, 
                                  CreateView, 
                                  UpdateView, 
                                  DeleteView)
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from users.models import User
from users.forms import UserRegisterForm
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.models import Group

class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        user = form.save()
        group, created = Group.objects.get_or_create(name='users')
        user.groups.add(group)
        return super().form_valid(form)


class UserListView(ListView):
    model = User
    permission_required = 'users.change_user'

@permission_required('users.change_user')
def ActivateUser(request, pk):
    user = User.objects.get(pk=pk)
    user.is_active = False if user.is_active else True
    user.save()
    return redirect('users:userslist')

users/templates/users/login.html
{% extends 'servise/base.html' %}
{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-3"></div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Вход
                        </h3>
                    </div> 
                    <div class="card-body">
                        {% csrf_token %}
                        {{form.as_p}}
                        <button type="submit" class="btn-success">Войти</button>
                    </div>
                    <div class="cardfooter"></div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'servise/base.html' %}
{% block content %}
    <div class="col-12">
        <form class="row" method="post" enctype="multipart/form-data">
            <div class="col-3"></div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Регистрация
                        </h3>
                    </div> 
                    <div class="card-body">
                        {% csrf_token %}
                        {{form.as_p}}
                        <button type="submit" class="btn-success">Регистрация</button>
                    </div>
                    <div class="cardfooter"></div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

users/templates/users/user_list.html
{% extends 'servise/base.html'%}

{% block content %}
<section class="py-5 text-center container">
    <h1 class="fw-light">Пользователи</h1>
</section>


<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for object in object_list %}
        <div class="col">
            <div class="card shadow-sm">
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center button">
                        <p class="card-text">{{object|title}}</p>
                    </div>
                    <div class="btn-group">
                        {% if object.is_active %}
                            <a href="{% url 'users:block' object.pk %}" type="button"class="btn btn-sm btn-outline-secondary">заблокировать</a>
                        {% else %}
                            <a href="{% url 'users:block' object.pk %}" type="button"class="btn btn-sm btn-outline-secondary">разблокировать</a>
                        {% endif %}
                    </div>    
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}