blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView
app_name = BlogConfig.name



urlpatterns = [
    path("blogs/", cache_page(60)(BlogListView.as_view()), name="blogs"),
    path("blog/detail/<int:pk>/", BlogDetailView.as_view(), name="detail")

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static 
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("servise.urls")),
    path('users/', include("users.urls", namespace='users')),
    path('blog/', include('blog.urls')),
]

servise/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from servise.views import (HomeView, 
                           ClientCreateView, ClientListView, ClientUpdateViev, ClientDeleteView,
                            MailSettingsListView, MailSettingsCreateView, MailSettingsUpdateViev, MailSettingsDeleteView,
                            ActivateMailSettings
)
from servise.jobs import test_job
from servise.forms import MailSettingsForm
from servise.apps import ServiseConfig
app_name = ServiseConfig.name

urlpatterns = [
    path('aaa/', test_job),
    path('', cache_page(60)(HomeView.as_view()), name='home'),
    path('/clients/', ClientListView.as_view(), name='Clients'),
    path('/clientcreate/', ClientCreateView.as_view(), name='Clientcreate'),
    path('/clientupdate/<int:pk>/', ClientUpdateViev.as_view(), name='Clientupdate'),
    path('/clientdelete/<int:pk>/', ClientDeleteView.as_view(), name='Clientdelete'),

    path('/mails/', MailSettingsListView.as_view(), name='Mails'), 
    path('/mailcreate/', MailSettingsCreateView.as_view(), name='Mailcreate'),
    path('/mailupdate/<int:pk>/', MailSettingsUpdateViev.as_view(), name='Mailupdate'),
    path('/maildelete/<int:pk>/', MailSettingsDeleteView.as_view(), name='Maildelete'),
    path("/mailblock/<int:pk>/", ActivateMailSettings, name="block")
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from users.views import RegisterView, UserListView, ActivateUser
from servise.views import HomeView
from users.apps import UsersConfig
app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('register/', RegisterView.as_view(), name="regyster"),
    path("userslist/", UserListView.as_view(), name="userslist"),
    path("userbloc/<int:pk>/", ActivateUser, name="block")
]

servise/models.py
from django.db import models
from users.models import NULLABLE, User
from django.db.models import TextChoices
from config.settings import AUTH_USER_MODEL



class Client(models.Model):
    email = models.EmailField(unique=True, verbose_name='почта')
    last_name = models.CharField(max_length=150, verbose_name='фамилия')
    first_name = models.CharField(max_length=150, verbose_name='имя')
    surname = models.CharField(max_length=150, verbose_name='отчество')
    comment = models.TextField(verbose_name='коментарий', **NULLABLE)
    user = models.ForeignKey(User,related_name="clients", on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f'{self.last_name} {self.first_name} {self.surname}, email: {self.email}'

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = "клиенты"
        ordering = ('first_name', 'last_name', 'surname')


class MailSettings(models.Model):

    periodicity = [
        ('d', 'day'),
        ('w', 'week'),
        ('m', 'month')
    ]
    status = [
        ('c', 'create'),
        ('s', 'start'),
        ('f', 'finish')
    ]
    
    title = models.CharField(max_length=150, verbose_name='тема письма', **NULLABLE)
    body = models.TextField(verbose_name='письмо')
    time = models.TimeField(auto_now=False, auto_now_add=False, verbose_name='время  начала рассылки')
    mailing_periodicity = models.CharField(max_length=40, verbose_name='периодичность', choices=periodicity)
    mailing_status = models.CharField(max_length=20, verbose_name='cтатус', default='c', choices=status)
    mailing_is_active = models.BooleanField(default=True, verbose_name='Рассылка активна')
    clients = models.ManyToManyField(Client, verbose_name='клиенты')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True, verbose_name='состояние')
    @property
    def get_clients_by_user(self):
        return Client.objects.filter(user=self.user)
    

    # def __str__(self) -> str:
    #     return f'Тема: {self.title} \
    #             Текст: {self.body},\
    #             Время: {self.time}, \
    #             Периодичность: {self.mailing_periodicity}, \
    #             Статус: {self.mailing_status}'

    class Meta:
        verbose_name = 'Настройки рассылки'
        verbose_name_plural = "Настройки рассылок"
        ordering = ('mailing_status', )


class Log(models.Model):
    last_try_date = models.DateTimeField(auto_now_add=True, verbose_name='дата и время попытки')
    try_status = models.CharField(max_length=250, verbose_name='статус попытки')
    server_response = models.CharField(max_length=250, verbose_name='ответ сервера', **NULLABLE)
    user = models.ForeignKey(Client, verbose_name='пользователь', on_delete=models.CASCADE)
    mail = models.ForeignKey(MailSettings, on_delete=models.CASCADE, verbose_name='рассылка')

    class Meta:
        verbose_name = 'Логи'
        verbose_name_plural = 'Логи'
        ordering = ('last_try_date', )

    def __str__(self) -> str:
        return f'Дата попытки: {self.last_try_date},' + \
               f'Статус: {self.try_status},' + \
               f'Ответ сервера: {self.server_response}'

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True, 'null': True}

class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')
    fio = models.CharField(max_length=150, verbose_name='ФИО')
    comment = models.TextField(verbose_name='коментарий', **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

servise/forms.py
from django import forms

from servise.models import Client, MailSettings

class ClientForm(forms.ModelForm):

    class Meta:
        model = Client
        fields = ('first_name', 'last_name', 'surname', 'email', 'comment')
        widgets = {
            'first_name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Имя клиента',
                }),

            'last_name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Фамилия клиента',
                }),

            'surname': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Отчество клиента',
                }),

            'email': forms.EmailInput(attrs={
                'class': 'form-control',
                'placeholder': 'Электронная почта клиента',
                }),

            'comment': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Ваш комментарий',
                'rows': 2,
                }),
        }


class MailSettingsForm(forms.ModelForm):

    class Meta:
        model = MailSettings
        fields = ('title', 'body','time', 'mailing_periodicity', 'mailing_status', 'clients')
        
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Тема сообщения',
                }),
            
            'body': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Текст сообщения',
                'rows': 2,
                }),
            'time': forms.TimeInput(attrs={
                'type': 'time',
                'class': 'form-control',
            }),
        }
    # choices = []
    # get_clients_by_user = forms.ChoiceField(choices=choices)

    # def __init__(self, *args, **kwargs):
    #     # only change attributes if an instance is passed            
    #     instance = kwargs.get('instance')
    #     if instance:
    #         self.choices = instance.get_clients_by_user()
    #         kwargs["initial"] = {'get_clients_by_user': instance.get_clients_by_user()}
    #     super().__init__(*args, **kwargs)

servise/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import (ListView, DetailView, TemplateView, 
                                  CreateView, UpdateView, DeleteView)
from django.urls import reverse_lazy, reverse
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.contrib.auth.decorators import permission_required
from django.forms import inlineformset_factory
from django.db import transaction
from django.http import Http404
from servise.models import Client, MailSettings
from servise.forms import ClientForm, MailSettingsForm
from blog.models import Blog
from users.models import User
import random


class HomeView(LoginRequiredMixin, TemplateView):
    template_name = "servise/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["object_list"] = Blog.objects.all()[0:3]
        context["users"] = User.objects.all().count()
        context["mailings"] = MailSettings.objects.all().count()
        context["clients"] = Client.objects.all().count()
        return context
    



class ClientListView(LoginRequiredMixin, ListView):
    model = Client
    def get_queryset(self, *args, **kwargs):
        queryset = Client.objects.filter(user=self.request.user)
        return queryset
        
class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy("servise:Clients")

    def form_valid(self, form):
        client = form.save(commit=False)
        client.user = self.request.user
        client.save()
        return super().form_valid(form)

class ClientUpdateViev(LoginRequiredMixin, UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy("servise:Clients")

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user:
            raise Http404
        return self.object

class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy("servise:Clients")

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user:
            raise Http404
        return self.object


class MailSettingsListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = MailSettings
    permission_required = 'servise.change_mailsettings'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["is_manager"] = self.request.user.groups.filter(name='manager').exists()
        return context
    

    def get_queryset(self, *args, **kwargs):
        queryset = MailSettings.objects.filter(user=self.request.user)
        if self.request.user.groups.filter(name='manager').exists():
            queryset = MailSettings.objects.all()
        return queryset


@permission_required('servise.change_mailsettings')
def ActivateMailSettings(request, pk):
    mailsettings = MailSettings.objects.get(pk=pk)
    mailsettings.is_active = False if mailsettings.is_active else True
    mailsettings.save()
    return redirect('servise:Mails')

class MailSettingsCreateView(LoginRequiredMixin, CreateView):
    model = MailSettings
    form_class = MailSettingsForm
    success_url = reverse_lazy("servise:Mails")

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['clients'] = Client.objects.filter(user=self.request.user)
        print(context)
        return context

    def form_valid(self, form):
        client = form.save(commit=False)
        client.user = self.request.user
        client.save()
        return super().form_valid(form)

class MailSettingsUpdateViev(LoginRequiredMixin, UpdateView):
    model = MailSettings
    form_class = MailSettingsForm
    success_url = reverse_lazy("servise:Mails")

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user:
            raise Http404
        return self.object

class MailSettingsDeleteView(LoginRequiredMixin, DeleteView):
    model = MailSettings
    success_url = reverse_lazy("servise:Mails")

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user:
            raise Http404
        return self.object
    

servise/templates/servise/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Album example · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/album/">



    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">


</head>

<body>

    <header>
        <div class="collapse bg-dark" id="navbarHeader">
            <div class="container">
                <div class="row">
                    <div class="col-sm-8 col-md-7 py-4">
                        <h4 class="text-white">About</h4>
                        <p class="text-muted">Add some information about the album below, the author, or any other
                            background context. Make it a few sentences long so folks can pick up some informative
                            tidbits. Then, link them off to some social networking sites or contact information.</p>
                    </div>
                    <div class="col-sm-4 offset-md-1 py-4">
                        <h4 class="text-white">Contact</h4>
                        <ul class="list-unstyled">
                            {% if user.is_authenticated %}
                                <li><a href="{% url 'servise:home' %}" class="text-white">Главная</a></li>
                                <li><a href="{% url 'blog:blogs' %}" class="text-white">Блоги</a></li>
                                <li><a href="{% url 'servise:Clients' %}" class="text-white">Менеджер клиентов</a></li>
                                <li><a href="{% url 'servise:Mails' %}" class="text-white">Менеджер рассылок</a></li>
                                <li><a href="{% url 'users:logout' %}" class="text-white">Выйти</a></li>
                                {% if perms.users.change_user %}
                                    <li><a href="{% url 'users:userslist' %}" class="text-white">Пользователи</a></li>
                                {% endif %}
                            {% else %}
                            <li><a href="{% url 'users:login' %}" class="text-white">Войти</a></li>
                            <li><a href="{% url 'users:regyster' %}" class="text-white">Регистрация</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="navbar navbar-dark bg-dark shadow-sm">
            <div class="container">
                <a href="#" class="navbar-brand d-flex align-items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                        stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2"
                        viewBox="0 0 24 24">
                        <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z" />
                        <circle cx="12" cy="13" r="4" />
                    </svg>
                    <strong>Album</strong>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </div>
    </header>

    <main>
        {% block content%}
        {% endblock %}
    </main>

    <footer class="text-muted py-5">
        <div class="container">
            <p class="float-end mb-1">
                <a href="#">Back to top</a>
            </p>
            <p class="mb-1">Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
            <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a
                    href="/docs/5.0/getting-started/introduction/">getting started guide</a>.</p>
        </div>
    </footer>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>


</body>

</html>

servise/templates/servise/client_confirm_delete.html
{% extends 'servise/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить клиента "{{object.email}}"?</p>
                        <button type="submit" class="btn-danger">Подтвердить</button>
                        <a href="{% url 'servise:Clients' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

servise/templates/servise/client_form.html
{% extends 'servise/base.html' %}
{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">

        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Клиент
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button type="submit" class="btn-success">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock %}

servise/templates/servise/client_list.html
{% extends 'servise/base.html'%}

{% block content %}
<section class="py-5 text-center container">
    <h1 class="fw-light">Клиенты</h1>
</section>


<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col-12 mb-5">
            <a class="btn btn-outline-primary" href="{% url 'servise:Clientcreate' %}">Добавить Клиента</a>
        </div>
        {% for object in object_list %}
        <div class="col">
            <div class="card shadow-sm">
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center button">
                        <p class="card-text">{{object|title}}</p>
                    </div>
                    <div class="btn-group">
                        <a href="{% url 'servise:Clientupdate' object.pk %}" type="button"
                            class="btn btn-sm btn-outline-secondary">update</a>
                        <a href="{% url 'servise:Clientdelete' object.pk %}" type="button"
                            class="btn btn-sm btn-outline-secondary">Delete</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

servise/templates/servise/home.html
{% extends 'servise/base.html'%}
{% block content %}
<section class="py-5 text-center container">
    <h1 class="fw-light">домашня страница</h1>
</section>

<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
       
    </div>
</div>
{% endblock %}

servise/templates/servise/mailsettings_confirm_delete.html
{% extends 'servise/base.html' %}
{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить Рассылку "{{object.title}}"?</p>
                        <button type="submit" class="btn-danger">Подтвердить</button>
                        <a href="{% url 'servise:Mails' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

servise/templates/servise/mailsettings_form.html
{% extends 'servise/base.html' %}
{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">

        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Рассылка
                    </h3>
                </div>
                <div class="card-body">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button type="submit" class="btn-success">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock %}

servise/templates/servise/mailsettings_list.html
{% extends 'servise/base.html'%}

{% block content %}
<section class="py-5 text-center container">
    <h1 class="fw-light">Рассылки</h1>
</section>


<div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col-12 mb-5">
            {% if not is_manager %}
            <a class="btn btn-outline-primary" href="{% url 'servise:Mailcreate' %}">Добавить Рассылку</a>
            {% endif %}
        </div>
        {% for object in object_list %}
        <div class="col">
            <div class="card shadow-sm">
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center button">
                        <p class="card-text">{{object|title}}</p>
                    </div>
                    <div class="btn-group">
                        {% if perms.servise.change_mailsettings and not is_manager %}
                        <a href="{% url 'servise:Mailupdate' object.pk %}" type="button"class="btn btn-sm btn-outline-secondary">update</a>
                        {% endif %}
                        {% if perms.servise.delete_mailsettings %}
                        <a href="{% url 'servise:Maildelete' object.pk %}" type="button"class="btn btn-sm btn-outline-secondary">Delete</a>
                        {% endif %}
                        {% if is_manager and object.is_active %}
                        <a href="{% url 'servise:block' object.pk %}" type="button"class="btn btn-sm btn-outline-secondary">заблокировать</a>
                        {% else %}
                        <a href="{% url 'servise:block' object.pk %}" type="button"class="btn btn-sm btn-outline-secondary">разблокировать</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}